<?php
/**
 * LocationApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * LocationApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LocationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1LocationQueryGet' => [
            'application/json',
        ],
        'v1LocationRealrouteStartCityIdDestinationCityIdGet' => [
            'application/json',
        ],
        'v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1LocationQueryGet
     *
     * @param  string $query query (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationQueryGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BingMapsRESTToolkitLocation
     */
    public function v1LocationQueryGet($query, string $contentType = self::contentTypes['v1LocationQueryGet'][0])
    {
        list($response) = $this->v1LocationQueryGetWithHttpInfo($query, $contentType);
        return $response;
    }

    /**
     * Operation v1LocationQueryGetWithHttpInfo
     *
     * @param  string $query (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationQueryGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BingMapsRESTToolkitLocation, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LocationQueryGetWithHttpInfo($query, string $contentType = self::contentTypes['v1LocationQueryGet'][0])
    {
        $request = $this->v1LocationQueryGetRequest($query, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\BingMapsRESTToolkitLocation' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\BingMapsRESTToolkitLocation' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BingMapsRESTToolkitLocation', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\BingMapsRESTToolkitLocation';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BingMapsRESTToolkitLocation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1LocationQueryGetAsync
     *
     * @param  string $query (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationQueryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationQueryGetAsync($query, string $contentType = self::contentTypes['v1LocationQueryGet'][0])
    {
        return $this->v1LocationQueryGetAsyncWithHttpInfo($query, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LocationQueryGetAsyncWithHttpInfo
     *
     * @param  string $query (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationQueryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationQueryGetAsyncWithHttpInfo($query, string $contentType = self::contentTypes['v1LocationQueryGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BingMapsRESTToolkitLocation';
        $request = $this->v1LocationQueryGetRequest($query, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1LocationQueryGet'
     *
     * @param  string $query (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationQueryGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LocationQueryGetRequest($query, string $contentType = self::contentTypes['v1LocationQueryGet'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling v1LocationQueryGet'
            );
        }


        $resourcePath = '/v1/location/{query}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($query !== null) {
            $resourcePath = str_replace(
                '{' . 'query' . '}',
                ObjectSerializer::toPathValue($query),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1LocationRealrouteStartCityIdDestinationCityIdGet
     *
     * @param  int $start_city_id start_city_id (required)
     * @param  int $destination_city_id destination_city_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute
     */
    public function v1LocationRealrouteStartCityIdDestinationCityIdGet($start_city_id, $destination_city_id, string $contentType = self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'][0])
    {
        list($response) = $this->v1LocationRealrouteStartCityIdDestinationCityIdGetWithHttpInfo($start_city_id, $destination_city_id, $contentType);
        return $response;
    }

    /**
     * Operation v1LocationRealrouteStartCityIdDestinationCityIdGetWithHttpInfo
     *
     * @param  int $start_city_id (required)
     * @param  int $destination_city_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LocationRealrouteStartCityIdDestinationCityIdGetWithHttpInfo($start_city_id, $destination_city_id, string $contentType = self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'][0])
    {
        $request = $this->v1LocationRealrouteStartCityIdDestinationCityIdGetRequest($start_city_id, $destination_city_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1LocationRealrouteStartCityIdDestinationCityIdGetAsync
     *
     * @param  int $start_city_id (required)
     * @param  int $destination_city_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationRealrouteStartCityIdDestinationCityIdGetAsync($start_city_id, $destination_city_id, string $contentType = self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'][0])
    {
        return $this->v1LocationRealrouteStartCityIdDestinationCityIdGetAsyncWithHttpInfo($start_city_id, $destination_city_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LocationRealrouteStartCityIdDestinationCityIdGetAsyncWithHttpInfo
     *
     * @param  int $start_city_id (required)
     * @param  int $destination_city_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationRealrouteStartCityIdDestinationCityIdGetAsyncWithHttpInfo($start_city_id, $destination_city_id, string $contentType = self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\FPHSpedVAPIObjectsMapsRealRoute';
        $request = $this->v1LocationRealrouteStartCityIdDestinationCityIdGetRequest($start_city_id, $destination_city_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1LocationRealrouteStartCityIdDestinationCityIdGet'
     *
     * @param  int $start_city_id (required)
     * @param  int $destination_city_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LocationRealrouteStartCityIdDestinationCityIdGetRequest($start_city_id, $destination_city_id, string $contentType = self::contentTypes['v1LocationRealrouteStartCityIdDestinationCityIdGet'][0])
    {

        // verify the required parameter 'start_city_id' is set
        if ($start_city_id === null || (is_array($start_city_id) && count($start_city_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $start_city_id when calling v1LocationRealrouteStartCityIdDestinationCityIdGet'
            );
        }

        // verify the required parameter 'destination_city_id' is set
        if ($destination_city_id === null || (is_array($destination_city_id) && count($destination_city_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $destination_city_id when calling v1LocationRealrouteStartCityIdDestinationCityIdGet'
            );
        }


        $resourcePath = '/v1/location/realroute/{startCityId}/{destinationCityId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($start_city_id !== null) {
            $resourcePath = str_replace(
                '{' . 'startCityId' . '}',
                ObjectSerializer::toPathValue($start_city_id),
                $resourcePath
            );
        }
        // path params
        if ($destination_city_id !== null) {
            $resourcePath = str_replace(
                '{' . 'destinationCityId' . '}',
                ObjectSerializer::toPathValue($destination_city_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet
     *
     * @param  int $start_branch_id start_branch_id (required)
     * @param  int $destination_branch_id destination_branch_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance
     */
    public function v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet($start_branch_id, $destination_branch_id, string $contentType = self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'][0])
    {
        list($response) = $this->v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetWithHttpInfo($start_branch_id, $destination_branch_id, $contentType);
        return $response;
    }

    /**
     * Operation v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetWithHttpInfo
     *
     * @param  int $start_branch_id (required)
     * @param  int $destination_branch_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetWithHttpInfo($start_branch_id, $destination_branch_id, string $contentType = self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'][0])
    {
        $request = $this->v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetRequest($start_branch_id, $destination_branch_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetAsync
     *
     * @param  int $start_branch_id (required)
     * @param  int $destination_branch_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetAsync($start_branch_id, $destination_branch_id, string $contentType = self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'][0])
    {
        return $this->v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetAsyncWithHttpInfo($start_branch_id, $destination_branch_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetAsyncWithHttpInfo
     *
     * @param  int $start_branch_id (required)
     * @param  int $destination_branch_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetAsyncWithHttpInfo($start_branch_id, $destination_branch_id, string $contentType = self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\FPHSpedVAPIObjectsLiveSGMDistance';
        $request = $this->v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetRequest($start_branch_id, $destination_branch_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'
     *
     * @param  int $start_branch_id (required)
     * @param  int $destination_branch_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGetRequest($start_branch_id, $destination_branch_id, string $contentType = self::contentTypes['v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'][0])
    {

        // verify the required parameter 'start_branch_id' is set
        if ($start_branch_id === null || (is_array($start_branch_id) && count($start_branch_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $start_branch_id when calling v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'
            );
        }

        // verify the required parameter 'destination_branch_id' is set
        if ($destination_branch_id === null || (is_array($destination_branch_id) && count($destination_branch_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $destination_branch_id when calling v1LocationScsmapDistanceStartBranchIdDestinationBranchIdGet'
            );
        }


        $resourcePath = '/v1/location/scsmap/distance/{startBranchId}/{destinationBranchId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($start_branch_id !== null) {
            $resourcePath = str_replace(
                '{' . 'startBranchId' . '}',
                ObjectSerializer::toPathValue($start_branch_id),
                $resourcePath
            );
        }
        // path params
        if ($destination_branch_id !== null) {
            $resourcePath = str_replace(
                '{' . 'destinationBranchId' . '}',
                ObjectSerializer::toPathValue($destination_branch_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
