<?php
/**
 * FPHSpedVAPIObjectsOMSIStationLink
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FPHSpedVAPIObjectsOMSIStationLink Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FPHSpedVAPIObjectsOMSIStationLink implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FPH.SpedV.API.Objects.OMSI.StationLink';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'map' => '\OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIMap',
        'start_cube_id' => 'int',
        'dest_cube_id' => 'int',
        'start_bus_stop' => '\OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop',
        'dest_bus_stop' => '\OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop',
        'length' => 'int',
        'source' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'map' => null,
        'start_cube_id' => 'int32',
        'dest_cube_id' => 'int32',
        'start_bus_stop' => null,
        'dest_bus_stop' => null,
        'length' => 'int32',
        'source' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'map' => true,
        'start_cube_id' => false,
        'dest_cube_id' => false,
        'start_bus_stop' => true,
        'dest_bus_stop' => true,
        'length' => false,
        'source' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'map' => 'map',
        'start_cube_id' => 'startCubeID',
        'dest_cube_id' => 'destCubeID',
        'start_bus_stop' => 'startBusStop',
        'dest_bus_stop' => 'destBusStop',
        'length' => 'length',
        'source' => 'source'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'map' => 'setMap',
        'start_cube_id' => 'setStartCubeId',
        'dest_cube_id' => 'setDestCubeId',
        'start_bus_stop' => 'setStartBusStop',
        'dest_bus_stop' => 'setDestBusStop',
        'length' => 'setLength',
        'source' => 'setSource'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'map' => 'getMap',
        'start_cube_id' => 'getStartCubeId',
        'dest_cube_id' => 'getDestCubeId',
        'start_bus_stop' => 'getStartBusStop',
        'dest_bus_stop' => 'getDestBusStop',
        'length' => 'getLength',
        'source' => 'getSource'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('map', $data ?? [], null);
        $this->setIfExists('start_cube_id', $data ?? [], null);
        $this->setIfExists('dest_cube_id', $data ?? [], null);
        $this->setIfExists('start_bus_stop', $data ?? [], null);
        $this->setIfExists('dest_bus_stop', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['map'] === null) {
            $invalidProperties[] = "'map' can't be null";
        }
        if ($this->container['start_cube_id'] === null) {
            $invalidProperties[] = "'start_cube_id' can't be null";
        }
        if ($this->container['dest_cube_id'] === null) {
            $invalidProperties[] = "'dest_cube_id' can't be null";
        }
        if ($this->container['start_bus_stop'] === null) {
            $invalidProperties[] = "'start_bus_stop' can't be null";
        }
        if ($this->container['dest_bus_stop'] === null) {
            $invalidProperties[] = "'dest_bus_stop' can't be null";
        }
        if ($this->container['length'] === null) {
            $invalidProperties[] = "'length' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets map
     *
     * @return \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIMap
     */
    public function getMap()
    {
        return $this->container['map'];
    }

    /**
     * Sets map
     *
     * @param \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIMap $map map
     *
     * @return self
     */
    public function setMap($map)
    {
        if (is_null($map)) {
            array_push($this->openAPINullablesSetToNull, 'map');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('map', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['map'] = $map;

        return $this;
    }

    /**
     * Gets start_cube_id
     *
     * @return int
     */
    public function getStartCubeId()
    {
        return $this->container['start_cube_id'];
    }

    /**
     * Sets start_cube_id
     *
     * @param int $start_cube_id start_cube_id
     *
     * @return self
     */
    public function setStartCubeId($start_cube_id)
    {
        if (is_null($start_cube_id)) {
            throw new \InvalidArgumentException('non-nullable start_cube_id cannot be null');
        }
        $this->container['start_cube_id'] = $start_cube_id;

        return $this;
    }

    /**
     * Gets dest_cube_id
     *
     * @return int
     */
    public function getDestCubeId()
    {
        return $this->container['dest_cube_id'];
    }

    /**
     * Sets dest_cube_id
     *
     * @param int $dest_cube_id dest_cube_id
     *
     * @return self
     */
    public function setDestCubeId($dest_cube_id)
    {
        if (is_null($dest_cube_id)) {
            throw new \InvalidArgumentException('non-nullable dest_cube_id cannot be null');
        }
        $this->container['dest_cube_id'] = $dest_cube_id;

        return $this;
    }

    /**
     * Gets start_bus_stop
     *
     * @return \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop
     */
    public function getStartBusStop()
    {
        return $this->container['start_bus_stop'];
    }

    /**
     * Sets start_bus_stop
     *
     * @param \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop $start_bus_stop start_bus_stop
     *
     * @return self
     */
    public function setStartBusStop($start_bus_stop)
    {
        if (is_null($start_bus_stop)) {
            array_push($this->openAPINullablesSetToNull, 'start_bus_stop');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_bus_stop', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_bus_stop'] = $start_bus_stop;

        return $this;
    }

    /**
     * Gets dest_bus_stop
     *
     * @return \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop
     */
    public function getDestBusStop()
    {
        return $this->container['dest_bus_stop'];
    }

    /**
     * Sets dest_bus_stop
     *
     * @param \OpenAPI\Client\Model\FPHSpedVAPIObjectsOMSIBusStop $dest_bus_stop dest_bus_stop
     *
     * @return self
     */
    public function setDestBusStop($dest_bus_stop)
    {
        if (is_null($dest_bus_stop)) {
            array_push($this->openAPINullablesSetToNull, 'dest_bus_stop');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dest_bus_stop', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dest_bus_stop'] = $dest_bus_stop;

        return $this;
    }

    /**
     * Gets length
     *
     * @return int
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param int $length length
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            array_push($this->openAPINullablesSetToNull, 'source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source'] = $source;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


