<?php
/**
 * FPHSpedVAPIObjectsOMSIBusStop
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FPHSpedVAPIObjectsOMSIBusStop Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FPHSpedVAPIObjectsOMSIBusStop implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FPH.SpedV.API.Objects.OMSI.BusStop';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'internal_name' => 'string',
        'internal_names' => 'string[]',
        'anzeige1' => 'string',
        'anzeige2' => 'string',
        'ibi_s1' => 'string',
        'ibi_s2' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'internal_name' => null,
        'internal_names' => null,
        'anzeige1' => null,
        'anzeige2' => null,
        'ibi_s1' => null,
        'ibi_s2' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'internal_name' => true,
        'internal_names' => true,
        'anzeige1' => true,
        'anzeige2' => true,
        'ibi_s1' => true,
        'ibi_s2' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'internal_name' => 'internalName',
        'internal_names' => 'internalNames',
        'anzeige1' => 'anzeige1',
        'anzeige2' => 'anzeige2',
        'ibi_s1' => 'ibiS1',
        'ibi_s2' => 'ibiS2'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'internal_name' => 'setInternalName',
        'internal_names' => 'setInternalNames',
        'anzeige1' => 'setAnzeige1',
        'anzeige2' => 'setAnzeige2',
        'ibi_s1' => 'setIbiS1',
        'ibi_s2' => 'setIbiS2'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'internal_name' => 'getInternalName',
        'internal_names' => 'getInternalNames',
        'anzeige1' => 'getAnzeige1',
        'anzeige2' => 'getAnzeige2',
        'ibi_s1' => 'getIbiS1',
        'ibi_s2' => 'getIbiS2'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('internal_name', $data ?? [], null);
        $this->setIfExists('internal_names', $data ?? [], null);
        $this->setIfExists('anzeige1', $data ?? [], null);
        $this->setIfExists('anzeige2', $data ?? [], null);
        $this->setIfExists('ibi_s1', $data ?? [], null);
        $this->setIfExists('ibi_s2', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['internal_name'] === null) {
            $invalidProperties[] = "'internal_name' can't be null";
        }
        if ($this->container['internal_names'] === null) {
            $invalidProperties[] = "'internal_names' can't be null";
        }
        if ($this->container['anzeige1'] === null) {
            $invalidProperties[] = "'anzeige1' can't be null";
        }
        if ($this->container['anzeige2'] === null) {
            $invalidProperties[] = "'anzeige2' can't be null";
        }
        if ($this->container['ibi_s1'] === null) {
            $invalidProperties[] = "'ibi_s1' can't be null";
        }
        if ($this->container['ibi_s2'] === null) {
            $invalidProperties[] = "'ibi_s2' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets internal_name
     *
     * @return string
     * @deprecated
     */
    public function getInternalName()
    {
        return $this->container['internal_name'];
    }

    /**
     * Sets internal_name
     *
     * @param string $internal_name internal_name
     *
     * @return self
     * @deprecated
     */
    public function setInternalName($internal_name)
    {
        if (is_null($internal_name)) {
            array_push($this->openAPINullablesSetToNull, 'internal_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('internal_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['internal_name'] = $internal_name;

        return $this;
    }

    /**
     * Gets internal_names
     *
     * @return string[]
     */
    public function getInternalNames()
    {
        return $this->container['internal_names'];
    }

    /**
     * Sets internal_names
     *
     * @param string[] $internal_names internal_names
     *
     * @return self
     */
    public function setInternalNames($internal_names)
    {
        if (is_null($internal_names)) {
            array_push($this->openAPINullablesSetToNull, 'internal_names');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('internal_names', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['internal_names'] = $internal_names;

        return $this;
    }

    /**
     * Gets anzeige1
     *
     * @return string
     */
    public function getAnzeige1()
    {
        return $this->container['anzeige1'];
    }

    /**
     * Sets anzeige1
     *
     * @param string $anzeige1 anzeige1
     *
     * @return self
     */
    public function setAnzeige1($anzeige1)
    {
        if (is_null($anzeige1)) {
            array_push($this->openAPINullablesSetToNull, 'anzeige1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('anzeige1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['anzeige1'] = $anzeige1;

        return $this;
    }

    /**
     * Gets anzeige2
     *
     * @return string
     */
    public function getAnzeige2()
    {
        return $this->container['anzeige2'];
    }

    /**
     * Sets anzeige2
     *
     * @param string $anzeige2 anzeige2
     *
     * @return self
     */
    public function setAnzeige2($anzeige2)
    {
        if (is_null($anzeige2)) {
            array_push($this->openAPINullablesSetToNull, 'anzeige2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('anzeige2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['anzeige2'] = $anzeige2;

        return $this;
    }

    /**
     * Gets ibi_s1
     *
     * @return string
     */
    public function getIbiS1()
    {
        return $this->container['ibi_s1'];
    }

    /**
     * Sets ibi_s1
     *
     * @param string $ibi_s1 ibi_s1
     *
     * @return self
     */
    public function setIbiS1($ibi_s1)
    {
        if (is_null($ibi_s1)) {
            array_push($this->openAPINullablesSetToNull, 'ibi_s1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ibi_s1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ibi_s1'] = $ibi_s1;

        return $this;
    }

    /**
     * Gets ibi_s2
     *
     * @return string
     */
    public function getIbiS2()
    {
        return $this->container['ibi_s2'];
    }

    /**
     * Sets ibi_s2
     *
     * @param string $ibi_s2 ibi_s2
     *
     * @return self
     */
    public function setIbiS2($ibi_s2)
    {
        if (is_null($ibi_s2)) {
            array_push($this->openAPINullablesSetToNull, 'ibi_s2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ibi_s2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ibi_s2'] = $ibi_s2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


