<?php
/**
 * FPHSpedVAPIObjectsLiveConvoyInfoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FPHSpedVAPIObjectsLiveConvoyInfoTest Class Doc Comment
 *
 * @category    Class
 * @description FPHSpedVAPIObjectsLiveConvoyInfo
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FPHSpedVAPIObjectsLiveConvoyInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FPHSpedVAPIObjectsLiveConvoyInfo"
     */
    public function testFPHSpedVAPIObjectsLiveConvoyInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sped_v_team_role_name"
     */
    public function testPropertySpedVTeamRoleName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tmp_staff_role_name"
     */
    public function testPropertyTmpStaffRoleName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "show_as_offline"
     */
    public function testPropertyShowAsOffline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steam_id"
     */
    public function testPropertySteamId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steam_pic"
     */
    public function testPropertySteamPic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "twitch_url"
     */
    public function testPropertyTwitchUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "discord_uid"
     */
    public function testPropertyDiscordUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bot_message"
     */
    public function testPropertyBotMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bot_task"
     */
    public function testPropertyBotTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bot_progress_max"
     */
    public function testPropertyBotProgressMax()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bot_progress_cur"
     */
    public function testPropertyBotProgressCur()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_game"
     */
    public function testPropertyScSGame()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_total_distance"
     */
    public function testPropertyScSTotalDistance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_current_distance"
     */
    public function testPropertyScSCurrentDistance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_odometer"
     */
    public function testPropertyScSOdometer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_max_fuel"
     */
    public function testPropertyScSMaxFuel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_act_fuel"
     */
    public function testPropertyScSActFuel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_velocity"
     */
    public function testPropertyScSVelocity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_speed_limit"
     */
    public function testPropertyScSSpeedLimit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_cruise_control"
     */
    public function testPropertyScSCruiseControl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_mp_server"
     */
    public function testPropertyScSMpServer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_est_arrival"
     */
    public function testPropertyScSEstArrival()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_damage_truck"
     */
    public function testPropertyScSDamageTruck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_damage_trailer"
     */
    public function testPropertyScSDamageTrailer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_damage_freight"
     */
    public function testPropertyScSDamageFreight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_truck_manufactor"
     */
    public function testPropertyScSTruckManufactor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_truck_model"
     */
    public function testPropertyScSTruckModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_truck_plate"
     */
    public function testPropertyScSTruckPlate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_x_coord"
     */
    public function testPropertyScSXCoord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_z_coord"
     */
    public function testPropertyScSZCoord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_near_by"
     */
    public function testPropertyScSNearBy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sc_s_scc_follow_user"
     */
    public function testPropertyScSSccFollowUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_weight"
     */
    public function testPropertyTaskWeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_freight"
     */
    public function testPropertyTaskFreight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_start"
     */
    public function testPropertyTaskStart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_dest"
     */
    public function testPropertyTaskDest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_start_company"
     */
    public function testPropertyTaskStartCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_dest_company"
     */
    public function testPropertyTaskDestCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "task_map"
     */
    public function testPropertyTaskMap()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_line"
     */
    public function testPropertyOmsILine()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_circ"
     */
    public function testPropertyOmsICirc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_dest"
     */
    public function testPropertyOmsIDest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_next"
     */
    public function testPropertyOmsINext()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_delay"
     */
    public function testPropertyOmsIDelay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oms_i_map"
     */
    public function testPropertyOmsIMap()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "st_w_anlage"
     */
    public function testPropertyStWAnlage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "st_w_cur_trains"
     */
    public function testPropertyStWCurTrains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "st_w_total_trains"
     */
    public function testPropertyStWTotalTrains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "st_w_cur_delay"
     */
    public function testPropertyStWCurDelay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_title"
     */
    public function testPropertySpotifyTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_artist"
     */
    public function testPropertySpotifyArtist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_album"
     */
    public function testPropertySpotifyAlbum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_cover_url"
     */
    public function testPropertySpotifyCoverUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_play_position"
     */
    public function testPropertySpotifyPlayPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "spotify_title_uri"
     */
    public function testPropertySpotifyTitleUri()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_server"
     */
    public function testPropertySimRailServer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_latitude"
     */
    public function testPropertySimRailLatitude()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_longitude"
     */
    public function testPropertySimRailLongitude()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_train_number"
     */
    public function testPropertySimRailTrainNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_train_velocity"
     */
    public function testPropertySimRailTrainVelocity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_train_next_stop"
     */
    public function testPropertySimRailTrainNextStop()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_train_destination"
     */
    public function testPropertySimRailTrainDestination()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sim_rail_dispatch_station"
     */
    public function testPropertySimRailDispatchStation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
