<?php
/**
 * FPHSpedVAPIAdminPermissionEnumTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FPHSpedVAPIAdminPermissionEnumTest Class Doc Comment
 *
 * @category    Class
 * @description 0 &#x3D; None  1 &#x3D; SeeLiveData  2 &#x3D; HandleScreenshots  4 &#x3D; HandleTaskCheck  8 &#x3D; TicketSystem  16 &#x3D; ViewData  32 &#x3D; ChangeData  64 &#x3D; BanUser  128 &#x3D; MapImport  256 &#x3D; KontorManagement  512 &#x3D; IsManagement
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FPHSpedVAPIAdminPermissionEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FPHSpedVAPIAdminPermissionEnum"
     */
    public function testFPHSpedVAPIAdminPermissionEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
