<?php
/**
 * FPHSpedVAPIEnumsUserChangeEntryTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpedV API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FPHSpedVAPIEnumsUserChangeEntryTypeTest Class Doc Comment
 *
 * @category    Class
 * @description 0 &#x3D; ChangedName  1 &#x3D; JoinedSpedition  2 &#x3D; DismissedBySpedition  3 &#x3D; Quitted  4 &#x3D; ChangedProfileData  5 &#x3D; FoundedSpedition  -1 &#x3D; NotSet
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FPHSpedVAPIEnumsUserChangeEntryTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FPHSpedVAPIEnumsUserChangeEntryType"
     */
    public function testFPHSpedVAPIEnumsUserChangeEntryType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
